FINAL_frappe_x1_001_fab4b7e0:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_002_3081a288:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_003_c3722b71:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_004_4412e5f6:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_005_3081a288:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_006_2f0da60e:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_007_4412e5f6:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_008_9b54a401:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400, 400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_009_c3722b71:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_010_4412e5f6:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_011_9e8953b4:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_012_27271336:
    batch_size: 4096
    block1_dropout: 0.1
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_013_4412e5f6:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_014_9b54a401:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400, 400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_015_27271336:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.1
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
FINAL_frappe_x1_016_b3bff621:
    batch_size: 4096
    block1_dropout: 0.2
    block1_hidden_activations: ReLU
    block1_hidden_units: [400]
    block2_dropout: 0.2
    block2_hidden_activations: ReLU
    block2_hidden_units: [400]
    block_type: 2B
    dataset_id: frappe_x1_47e6e0df
    debug_mode: false
    early_stop_patience: 2
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    eval_interval: 1
    feature_specs: null
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FINAL
    model_id: FINAL_default
    model_root: ./checkpoints/FINAL_frappe_x1/
    monitor: AUC
    monitor_mode: max
    net_regularizer: 0
    batch_norm: True
    num_workers: 3
    optimizer: adam
    ordered_features: null
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_field_gate: true
    verbose: 1
