DeepFM_avazu_x1_004_514a2b87:
    batch_norm: true
    batch_size: 4096
    dataset_id: avazu_x1_3fb65689
    debug: false
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Avazu/DeepFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1