DCNv2_criteo_x1_001_28c60688:
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: parallel
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [400, 400, 400]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
