DCNv2_amazonelectronics_x1_014_3d86d84a:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.005
    epochs: 100
    eval_interval: 1
    group_index: user_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    low_rank: 32
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./checkpoints/DCNv2_amazonelectronics_x1/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_low_rank_mixture: false
    verbose: 1
DCNv2_amazonelectronics_x1_026_3f36bb39:
    batch_norm: true
    batch_size: 1024
    dataset_id: amazonelectronics_x1_b7a43f49
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_interval: 1
    group_index: user_id
    learning_rate: 0.0005
    loss: binary_crossentropy
    low_rank: 32
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./checkpoints/DCNv2_amazonelectronics_x1/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2022
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_low_rank_mixture: false
    verbose: 1
