HOFM_kkbox_x1_001_b3c49286:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 128]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_002_0b04fd80:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 64]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_003_83bd25ec:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 32]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_004_4a8dfec8:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 128]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_005_887fd1c6:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 64]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_006_69b5b673:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 32]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_007_2e45fd9d:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 128]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_008_2d0ee6bb:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 64]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_009_4b0da798:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 32]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-05
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_010_de36de4c:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 128]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_011_80a3f9a7:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 64]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_012_06acb452:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 32]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.0001
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_013_e8bb1ff4:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 128]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.001
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_014_15a96413:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 64]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.001
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
HOFM_kkbox_x1_015_927f0730:
    batch_size: 10000
    dataset_id: kkbox_x1_227d337d
    debug: false
    embedding_dim: [128, 32]
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: HOFM
    model_id: HOFM_base
    model_root: ./KKBox/HOFM_kkbox_x1/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    order: 3
    patience: 2
    pickle_feature_encoder: true
    regularizer: 0.001
    reuse_embedding: false
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
