DeepFM_criteo_x1_001_4b788fed:
    batch_norm: true
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ./Criteo/DeepFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 0
